### PR TITLE
Move provider_prefix to key extension

### LINKED ISSUE #224: s2s key db collection should have provider_prefix, owner, is_admin, is_provider_admin in the root
~It should only have it in the `extension` section.~

Lets have s2skey's `user_info` as similar as possible to the `user_info` retrieved by analyzing idp tokens. Lets move `provider_prefix` OUT of `user_info` into the root, as well as `owner` and `is_provider_admin` and `is_admin`.

### PR DESCRIPTION
**Pull request by litvaOo**
resolves #224

### CODE REVIEW

**Comment by shlomi-nx** [comment]
@litvaOo Please also provide a mongo snippet to fix existing s2s keys

**Comment by litvaOo** [comment]
@shlomi-nx ok, got it

**Comment by litvaOo** [comment]
@shlomi-nx 
Here is the snippet for updating old keys
```
db.s2skey.find(
    {
        $and: [
            {"provider_prefix": {$ne: null}},
            {"extension.provider_prefix": null}
        ] 
    }, { provider_prefix: 1}
    ).toArray().map(
        x => db.s2skey.update(
            { _id: x._id }, 
            { $set: {
                "extension.provider_prefix": x.provider_prefix },
                $unset: { "provider_prefix": "" }
                }
            )
        )
```

**Comment by shlomi-nx** [comment]
@litvaOo This looks very good, however, I seem to have made a mistake defining this issue..

What I meant to do was to keep s2skey's `user_info` as similar as possible to the `user_info` retrieved by analyzing idp tokens. So actually, what we need is to move `provider_prefix` OUT of `user_info` into the root, as well as `owner` and `is_provider_admin` and `is_admin`. 

Sorry for the confusion!

**Pull request closed without merging**
